#!/bin/bash

echo "------------------------------Engineering and Computer Science------------"
./distance0
echo "------------------------------input1.txt-------------------------"
./distance
echo "------------------------------input2.txt-------------------------"
./distance2
echo "------------------------------input3.txt-------------------------"
./distance3
