#!/bin/bash

counter=1
echo "-----------------------------Hasthtable----------------------"
./hashtable 100000

echo "---------------------------MST (Sparse Tree)----------------"
./mst

echo "--------------------------MST(Dense Tree)-------------------"
./mst2

echo "--------------------------Extra-Credit (N = 1000)-----------"
./extra_credit 100000
